### PR TITLE
Use PDF mirror since juscaba uses wrong mime type

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by xaiki** [comment]
Note that you could also download from juscaba using the file api and send it back to the user correcting the mime type...

**Comment by seppo0010** [comment]
Yeah. I guess. It's more work. And I'd also prefer to have a mirror anyway.

**Comment by seppo0010** [comment]
Actually... can you do that? don't they have to have CORS enabled?

**Comment by xaiki** [comment]
this can probably now be closed can't it ?

**Review by xaiki — CHANGES_REQUESTED** [review]
close ?

**Comment by xaiki** [comment]
i can't believe io is so complicated in go...

**Pull request merged**
