### PR TITLE
Fix warning when actuacion does not have an actId

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by xaiki** [comment]
Prob needs the same change in ts

**Comment by seppo0010** [comment]
I don't see where... ts has documentos this is actuaciones

**Comment by xaiki** [comment]
We index on actid

**Comment by seppo0010** [comment]
ok, all documentos have actId, actuaciones without actId have no documentos?

**Comment by seppo0010** [comment]
ah, wait... I see what you are saying, let me check

**Pull request merged**
